name: doce_blocks
description: A project for Docebo Hackaton 2020

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^6.0.1
  flutter_svg: ^0.18.1
  rxdart: ^0.24.1
  equatable: ^1.2.2
  uuid: ^2.2.0
  responsive_builder: ^0.2.0+2
  shared_preferences: ^0.5.8

  firebase_core: ^0.4.5
  firebase_core_web: ^0.1.1+2

  firebase_auth: ^0.15.2
  firebase_auth_web: ^0.1.3+1

  cloud_firestore: ^0.13.7
  cloud_firestore_web: ^0.1.1+2

  cupertino_icons: ^0.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/empty_slate.svg
    - assets/empty_slate_section.svg
    - assets/icon_article.svg
    - assets/icon_list.svg
    - assets/icon_video.svg
    - assets/login.png
